---
- hosts      : all
  connection : local

  vars_files:
    - defaults/main.yml

  tasks:

    # Check that this is a supported device
    - import_tasks : tasks/device-check.yml

    # Installation and Configuration
    - import_tasks : tasks/raspbian/packages.yml
    - import_tasks : tasks/raspbian/locale.yml

    # Optimizations
    - import_tasks : tasks/rpi3/device-optimizations.yml
    - import_tasks : tasks/rpi3/retroarch-optimizations.yml
    - import_tasks : tasks/rpi3/rice-optimizations.yml
    - import_tasks : tasks/rpi3/glide-optimizations.yml

    # Configurations
    - import_tasks : tasks/config/n64-retrolink-controllers.yml


    # Remind user to reboot if in debug mode
    - name  : Reboot
      debug :
        msg : Don't forget to reboot your RaspberryPi!
