# Manages packages needed for Raspbian
---

- name  : Operating System Packages
  block :

    - name           : Updating Operating System Packages
      become         : yes
      apt            :
        upgrade      : dist
        update_cache : yes

    - name         : Removing Old Package Dependencies
      become       : yes
      apt          :
        autoremove : yes

  when : not skip_os_packages|default(retropie_defaults.skip_os_packages)
